# Generated by Django 5.2.4 on 2025-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_details',
            field=models.TextField(blank=True),
        ),
    ]
